Import('env')

kenv = env.Clone()
kenv.Append(CPPPATH   = ['include'],
            CCFLAGS   = ['-ffreestanding'],
            LINKFLAGS = ['-nostdlib', '-Tkernel/link.ld'])

kernel = kenv.Program('kernel.bin', Glob('*.c')   + Glob('*.asm') +
                                    Glob('*/*.c') + Glob('*/*.asm'))

Depends(kernel, 'link.ld')
Return('kernel')
