from os import popen
Import('env', 'ARCH')

kenv = env.Clone()
kenv.AppendUnique(CPPPATH   = ['include'],
                  CPPFLAGS  = [('-isystem', 'kernel/include/lib')],
                  CCFLAGS   = ['-ffreestanding', '-fbuiltin'],
                  LINKFLAGS = ['-nostdlib', '-Tkernel/arch/%s/linker.ld' % ARCH],
                  LIBS      = ['gcc'])

kernel = kenv.Program('kernel.elf', Glob('*.c') + Glob('*/*.c') + Glob('*.sx') + Glob('*/*.sx') +
                                    Glob('arch/%s/*.c'  % ARCH) + Glob('arch/%s/*/*.c'  % ARCH)  +
                                    Glob('arch/%s/*.sx' % ARCH) + Glob('arch/%s/*/*.sx' % ARCH))
Return('kernel')
